//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozac()
        {
            this.PutniNalogs = new HashSet<PutniNalog>();
        }
    
        public int IDVozac { get; set; }
        public string Name { get; set; }
        public int BrojMobitela { get; set; }
        public int BrojVozackeDozvole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PutniNalog> PutniNalogs { get; set; }
    }
}
